version: '3'

services:
  web:
    build: .
    container_name: web
    command: bash entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - project-pgdata:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
    depends_on:
      - web

volumes:
  project-pgdata:
