# Generated by Django 4.0.6 on 2022-07-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_id', models.ManyToManyField(blank=True, null=True, to='catalog.product')),
                ('self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='FilialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_prices', to='catalog.filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_prices', to='catalog.product')),
            ],
            options={
                'unique_together': {('product', 'filial')},
            },
        ),
    ]
