# Generated by Django 4.0.6 on 2022-07-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='product_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='characteristics', to='catalog.product'),
        ),
    ]
