# Generated by Django 4.0.6 on 2022-07-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_characteristic_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='product_id',
            field=models.ManyToManyField(related_name='characteristics', to='catalog.product'),
        ),
    ]
